---
ansible_connection: local
openshift_cluster_content:
- galaxy_requirements: "{{ playbook_dir }}/galaxy_requirements.yml"
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "{{ playbook_dir }}/openshift-templates/jenkins-s2i-build/template.yml"
    params: "{{ playbook_dir }}/params/jenkins/build"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins
  - name: hoverfly
    template: "{{ playbook_dir }}/openshift-templates/docker-build/template.yml"
    params: "{{ playbook_dir }}/params/hoverfly/build"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - hoverfly
  - name: sonarqube
    template: "{{ playbook_dir }}/openshift-templates/docker-build/template.yml"
    params: "{{ playbook_dir }}/params/sonarqube/build"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - sonarqube     
- object: jenkins-slave-nodes
  content:
  - name: jenkins-slave-ansible
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/ansible"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - ansible-slave
  - name: jenkins-slave-python
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/python"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - python-slave
  - name: jenkins-slave-arachni
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/arachni"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - arachni-slave
  - name: jenkins-slave-zap
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/zap"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins-slaves
    - zap-slave
- object: ci-cd-deployments
  content:
  - name: sonarqube
    template: "{{ playbook_dir }}/openshift-templates/sonarqube/template.yml"
    params: "{{ playbook_dir }}/params/sonarqube/deploy"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - sonarqube
    - sonarqube-deploy
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params: "{{ playbook_dir }}/params/sonarqube/postgresql"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - sonarqube
    - sonarqube-postgresql
    - sonarqube-postgresql-deploy
  - name: nexus
    template: "{{ playbook_dir }}/openshift-templates/nexus/template.yml"
    params: "{{ playbook_dir }}/params/nexus/deploy"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - nexus
    - nexus-deploy
    post_steps:
    - role: "ci-cd/roles/configure-nexus"
  - name: jenkins-persistent
    template: "{{ playbook_dir }}/openshift-templates/jenkins/jenkins-persistent-template.yml"
    params: "{{ playbook_dir }}/params/jenkins/deploy"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins
    - jenkins-deploy
  - name: hoverfly
    template: "{{ playbook_dir }}/openshift-templates/hoverfly/template.yml"
    params: "{{ playbook_dir }}/params/hoverfly/deploy"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - hoverfly
    - hoverfly-deploy
