---
ansible_connection: local
openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params_from_vars: "{{ ci_cd }}"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params_from_vars: "{{ dev }}"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params_from_vars: "{{ test }}"
    tags:
    - projects
- object: group-role-binding
  content:
  - name: "ci-cd-acl"
    namespace: "{{ ci_cd.NAMESPACE }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params_from_vars: "{{ role_binding_group }}"
    tags:
    - rolebinding-group
  - name: "{{ dev.NAMESPACE }}-acl"
    namespace: "{{ dev.NAMESPACE }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params_from_vars: "{{ role_binding_group }}"
    tags:
    - rolebinding-group
  - name: "{{ test.NAMESPACE }}-acl"
    namespace: "{{ test.NAMESPACE }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params_from_vars: "{{ role_binding_group }}"
    tags:
    - rolebinding-group